# Blog settings
permalink: /blog/:title

#project pages workaround
baseurl: /project-portfolio
# baseurl: ''

# My variables
name: Johna Paolino
description: UX Design
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
